name: Auto Generate Pages Index

on:
  push:
    paths:
      - 'pages/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: node gen-pages-index.js